#This file contains the CLIENT_KEY & CLIENT_SECRET for Google OmniAuth 2.0

development:
  client_key: 'cd7dfcf45b07f2b18558'
  client_secret: '75c264a9cfd49f6ec4370245db5477f37ef401be'

test:
  client_key: 'qwerty12345'
  client_secret: 'db117b422bfaa2a4c4038921db2634ce56ceeb09'

# Set these to appropriate values when deploying to production
production:
  client_key: <%= ENV['GITHUB_KEY'] %>
  client_secret: <%= ENV['GITHUB_SECRET'] %>
