#This file contains the CLIENT_KEY & CLIENT_SECRET for Google OmniAuth 2.0

development:
  client_key: 'bf03d576759db35d16cd'
  client_secret: '9d906be3c24dd9cb839de8d122b0d0247ee8ddd4'

test:
  client_key: '112233445566'
  client_secret: '112233445566'

# Set these to appropriate values when deploying to production
production:
  client_key: <%= ENV['GITHUB_KEY'] %>
  client_secret: <%= ENV['GITHUB_SECRET'] %>
